### ISSUE TITLE
Main Screen UI setup

### ISSUE THREAD

**Issue by jzho987** [SOFTENG310-Team3/A1-project#25]
Create and setup the FXML file for "Main Screen"  scene. Include element ids, and function name for controller.

**Comment by ochu761** [comment]
Approved

**Comment by ochu761** [comment]
Closed with the completion of Main screen FXML and Controller setup in [5e10cbb](https://github.com/SOFTENG310-Team3/A1-project/commit/5e10cbbb0a58ca7d4a81132470034509b222d826)
