### ISSUE TITLE
Scenes cut off at bottom of app window

### ISSUE THREAD

**Issue by ochu761** [SOFTENG310-Team3/A1-project#36]
**Location**: every scene using FXML

**Observed behaviour**: margins defined and displayed in SceneBuilder do not visually align with that displayed in the application window

**Operating system**: MacOS

**Steps to reproduce**:
1. Open MainScreen.fxml in SceneBuilder and observe the bottom margin of the Rewards button
2. Launch the application and navigate to the Main Screen via Dashboard and take note of the reduced bottom margin3. 

Also noticeable in the Home screen where the bottom margin is smaller than defined.

**Potential cause**: this might be due to the menu bar being counted as part of the window size, pushing the screen elements further down than expected. May also be an OS-specific issue.
There might be some way to programmatically set the bounding box to calculate window/scene dimensions

**Screenshots**:
Scenebuilder margin
<img width="303" alt="Screen Shot 2022-08-18 at 2 06 57 PM" src="https://user-images.githubusercontent.com/79777245/185276443-f1946695-d204-442b-87ae-562b274b373e.png">

Application window margin
<img width="698" alt="Screen Shot 2022-08-18 at 2 06 30 PM" src="https://user-images.githubusercontent.com/79777245/185276396-15422538-0258-448b-b16e-6507a5735be1.png">

**Comment by poli648** [comment]
Having the same issue on a windows machine would be good to get it fixed. Approved

**Comment by jzho987** [comment]
This bug exist because the top bar that windows add in pushes all the elements down by a few pixels and then cuts off at the bottom because the screen size is fixed.
If we just add a padding to the bottom of the left V-Box, the issue will be resolved. But I will check if there is a better solution for it that is not hard coded.

**Comment by jzho987** [comment]
#49 referenced pull request

**Comment by jzho987** [comment]
Pull request approved, #49 Closing issue
