### ISSUE TITLE
Implement basic functionalities in "New task" scene

### ISSUE THREAD

**Issue by jzho987** [SOFTENG310-Team3/A1-project#42]
- [x] Implement close button, where when clicked, the task pop up will be closed and back to the main screen
- [x] Implement Add Task button, where when clicked, the current task saved into an object to be added to the task list
- [x] Implement toggle functionality, where the toggle buttons will be untoggled when another toggle button is clicked.

**Comment by poli648** [comment]
Will assign myself and get on to finishing this controller
