### ISSUE TITLE
CSS not being applied to Task Scene

### ISSUE THREAD

**Issue by poli648** [SOFTENG310-Team3/A1-project#44]
**Location**: Task.fxml

**Observed behaviour**: CSS styling is not being applied to the popup scene

**Operating System**: Windows 11

**Steps to reproduce**:

1. Open the Task.fxml scene from the MainScreen.fxml scene. 
2. Observe the lack of CSS style applied to the popup scene

**Potential cause**: This may be because the task.css file is not being applied to the popup window on the startup

**Screenshots**:
![image](https://user-images.githubusercontent.com/79772678/185730428-6900b759-db8f-4d93-9a5f-2040196b5189.png)

**Comment by ochu761** [comment]
Just checked MainScreen.css and seems to work fine by adding stylesheets="@MainScreen.css" to the root element (AnchorPane) in MainScreen.fxml. Not sure if can be applied to Task.fxml.


Approved by Ou-An
