### ISSUE TITLE
Add Task Object to Main Screen "Current Tasks" ListView

### ISSUE THREAD

**Issue by ochu761** [SOFTENG310-Team3/A1-project#45]
Large issue of high priority requiring at least two developers to complete the following subtasks:

- [x] Create VBox or ListView FXML elements to display Task items in "Current Tasks" and "Completed Tasks" @jzho987
- [x] Create Lists to store current and completed Task objects @ochu761
- [x] addTask() and removeTask() methods to modify FXML elements.

**Comment by jzho987** [comment]
Good necessary issue, approved!
