### ISSUE TITLE
Fix CSS inconsistencies (as of 22 Aug)

### ISSUE THREAD

**Issue by ochu761** [SOFTENG310-Team3/A1-project#53]
- [ ] White corner backgrounds on rounded border (Task Screen)

Please edit and add minor CSS issues if you find any here

**Comment by oeng099** [comment]
Good issue to bring up in terms of user interfacing and user experience. Will help in making the application more consistent and professional.

**Comment by WiktorTumilowicz** [comment]
Issue has been adressed.
