### ISSUE TITLE
Add name field to Task UI and class

### ISSUE THREAD

**Issue by ochu761** [SOFTENG310-Team3/A1-project#63]
Each task list item (in the Main screen) currently shows "TASK NAME" as there is currently no way to assign a name to a task.

- [x] Add name input field in FXML (with appropriate id)
- [x] Add name field for Task model class (including getters and setters)
- [x] Display Task name on each task item (by calling name getter from MainScreenController)

**Comment by samanthamebius** [comment]
A very important issue to fix, looks like you've broken it down well and have a good plan to address the issue
