### ISSUE TITLE
Grey out scene out of focus in background.

### ISSUE THREAD

**Issue by WiktorTumilowicz** [SOFTENG310-Team3/A1-project#76]
Make the scene which is not in focus grey out a little bit so that it is obvious to the user which scene they can interact with.
For example, when a "new task" window is opened the out of focus "main scene" should have a grey tint over it to show that you cannot interact with it in the present moment.

**Comment by oeng099** [comment]
I think this is a good issue to address particularly in terms of user experience and usability. Approved.
