### ISSUE TITLE
Category filter buttons not showing as unclicked when clicked again.

### ISSUE THREAD

**Issue by oeng099** [SOFTENG310-Team3/A1-project#97]
The buttons used for sorting by category reset all sorting when the current category button is clicked. However this does not update on the Categories button section despite all tasks reappearing.

**Comment by WiktorTumilowicz** [comment]
I do not understand this issue, could you elaborate further/ give examples?

**Comment by oeng099** [comment]
So currently, when started the buttons in the category section will appear like this:
![image](https://user-images.githubusercontent.com/79787985/196302128-aaca392c-e8e8-4ab1-97de-0cfe1fb59201.png)

Once clicked, the specific button clicked will have its style changed like this:
![image](https://user-images.githubusercontent.com/79787985/196302208-2f1c03fd-aea3-476d-84d3-9381f6cad2e3.png)

When the currently selected button, in this case Work, is clicked on again, it should return to the same style as School and Home as clicking the currently selected button will reset the filter and show all tasks of any category.

**Comment by WiktorTumilowicz** [comment]
That makes a lot more sense now, I think this is a good issue and I would love to see it implemented! Maybe make it so when the 'categories' drop down is pressed the filter is also reset?

**Comment by WiktorTumilowicz** [comment]
Nevermind that is not how the categories button works my bad.
