### ISSUE TITLE
File structure is a mess

### ISSUE THREAD

**Issue by WiktorTumilowicz** [SOFTENG310-Team3/A1-project#98]
There is no structure to the files in the project, fxml, resources(images), css and java files should all be kept separate from each other. However this is not currently the case.
In addition, the project only runs on eclipse and it should be restructred using maven such that all IDE's can run the project.

**Comment by oeng099** [comment]
Good issue! This would really help to increase the modifiability and overall maintainability of the code. Having it be less IDE dependent would also be very useful.

**Comment by WiktorTumilowicz** [comment]
Completed. I can now use Intellij to work on the project :)
